### ISSUE TITLE
Enable all tests in bratio.spec and fix bratio as needed.

### ISSUE THREAD

**Issue by bwahl** [PanthR/panthrMath#42]
For example, when x = 0.135335283, a = 0.0000453999, and b = 8103.0839276, we get the message, "repeat returned NaN."

**Comment by skiadas** [comment]
Trouble case now:

x = 0.06766764
a= 20.08554
b= 22026.47

This causes a tailFlip first and becomes:

x = 0.93233236
b= 20.08554
a= 22026.47

Goes into the min(a,b) > 1 cases, then b <= 40 cases, then it fails the b*x < 0.7. This sends it to bgrat.

In R code, they added an exception on 2010-03-18 to send it to bpser instead of bgrat on some very extreme conditions, which this example qualifies. Comment in their commit is:   "another extreme tail pbeta(*, log.p) case: PR#14230"

**Comment by skiadas** [comment]
Current bottleneck:

x = 0.9323324
a= 22026.47
b= 20.08554

heads into bpser for large lambda

**Comment by skiadas** [comment]
Closing, passes all tests now.
